# Generated by Django 5.2.3 on 2025-06-16 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Укажите место, в котором необходимо выполнять привычку",
                        max_length=200,
                        null=True,
                        verbose_name="Место",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        blank=True,
                        help_text="Укажите время, когда необходимо выполнять привычку",
                        null=True,
                        verbose_name="Время",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите действие, которое представляет собой привычку",
                        max_length=200,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_good_habit",
                    models.BooleanField(
                        default=False, verbose_name="Приятная привычка"
                    ),
                ),
                (
                    "frequency",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Периодичность"
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Чем пользователь должен себя вознаградить после выполнения",
                        max_length=200,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "duration",
                    models.SmallIntegerField(
                        help_text="Время, которое предположительно потратит пользователь на выполнение привычки в минутах",
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Публичность"),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
            },
        ),
    ]
